# Generated by Django 3.2.16 on 2023-06-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACCOUNT',
        ),
    ]
