# Generated by Django 3.2.16 on 2023-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RECEIPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_descriptions', models.TextField()),
                ('receipe_iamge', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
