# Generated by Django 3.2.16 on 2023-06-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20230602_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('speed', models.IntegerField(default=50)),
            ],
        ),
    ]
